name: Checkout

on: [push]

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
  
        - name: List files
          run: ls -a
        - name: Checkout
          uses: actions/checkout@v3
           
        - name: List FIles after 
          run: ls -a
            