name: Manually triggered

on: 
    workflow_dispatch:
        inputs:
            string:
                description: a string input to echo 
                type: string
                required: true
                default: "Default value"
        

jobs: 
    log-info:
        runs-on: ubuntu-latest
        steps: 
            - run: echo $GITHUB_REF