name: Manually triggered

on: 
    workflow_dispatch:
        inputs:
            string:
                description: a string input to echo 
                type: string
                required: true
                default: "Default value"
            number:
                description: A number input
                default: 4
                type: number
            option:
                description: An optional input
                required: true
                default: "Option 3"
                type: choice
                options:
                    - Option 1
                    - Option 2
                    - Option 3
                    - option 4 
            boolean: 
                description: A boolean input
                required: false
                type: boolean
            evironment:
                description: An environment variable
                type: environment
                required: true
        

jobs: 
    log-info:
        runs-on: ubuntu-latest
        steps: 
            - run: echo $GITHUB_REF