name: Reusable Workflow outputs

on: 
    workflow_call:
        outputs:
            date:
                description: "The date the workflow was run"
              
                value: ${{ jobs.generate-ouputs.outputs.date }}

jobs: 
    nested-wf:
        uses: chris281854/pruebacdci/.github/workflows/reusablewf.yml@main

        with:
            name: ${{ github.event.inputs.name }}
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN }}
    generate-ouputs:
        runs-on: ubuntu-latest
        #mapping outputs of th wf with the outputs of the job
        outputs:
            date: ${{ steps.date-step.outputs.date }}
        steps:
            - run: echo "date=$(date)" >> $GITHUB_OUTPUT
              id: date-step
