name: Variables and Secrets

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
            ENV_LEVELE_VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
        steps:
            - name: Run only if BOOLEAN_SECRET is true
              if: vars.BOOLEAN_SECRET == 'true'
              run: echo "This will run only if BOOLEAN_SECRET is true"
            - name: Log vars
              run: |
                    echo "ENV_LEVELE_VAR: $ENV_LEVELE_VAR"
                    echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
            - name: "Run only if BOOLEAN_SECRET is true"
              if: ${{ vars.BOOLEAN_SECRET == 'true' }}
              run: echo "This will run only if BOOLEAN_SECRET is true"
            - name: "Log vars"
              run: |
                echo "ENV_LEVELE_VAR: $ENV_LEVELE_VAR"
                echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"

